version: "3.8"
services:
    load_balancer:
        build: load_balancer
        ports:
            - "80:80"
        links:
            - react
            - express
    react:
        build: frontend
    express:
        build: backend
        links:
            - cache
            - database
    cache:
        image: redis:6.2.3-buster
    database:
        image: mongo:4.4.6
