version: "3"
services:
    load_balancer:
        build: load_balancer
        ports:
            - "443:443"
        links:
            - react
            - express
        volumes:
            - /home/jack/ssl:/home/jack/ssl
    react:
        build: frontend
    express:
        build: backend
        links:
            - cache
            - database
    cache:
        image: redis:6.2.3-buster
    database:
        image: mongo:4.4.6
