<div class="core-cont">
    <h3 class="ml-2">Welcome!</h3>
    <hr class="bg-dark" />
    <div id="introduction">
        <img class="mr-3 img-thumbnail img-responsive float-left" width="250px" height="250px" src="assets/img/me.png" alt="A picture of me" />
        <p>Hello, my name is Jack Whelan and I'm currently in my final year studying Computer Science in Technological University Dublin (formerly DIT). I am broadly interested in Computer Science and am constantly learning about as many different areas as I can in order to maximise my usefulness and flexibility within teams.</p>
        <p>If you want to know a little bit more about me, take a look at the <a href="about">about</a> page linked in the navigation bar above.</p>
        <p>If you want to know about my personal projects, check out the <a href="projects">projects</a> page. Some of my projects are not open source on GitHub for security reasons but those that are can be viewed <a href="https://github.com/jackwhelan/">here.</a></p>
        <p>If you would like to hear about my past work experience and what my previous roles and responsibilities were, check out the <a href="work">work experience</a> page.</p>
    </div>
</div>

<div class="core-cont">
    TEST
</div>