<!DOCTYPE html>
<html>

<head>
    <base href="/" />
    <title><?= $title ?> | <?= $local_title ?></title>
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/core.css" />
</head>

<body class="d-flex flex-column">
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#"><?= $title ?><span class="text-muted"> | <?= $local_title ?></span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navBarToggler" aria-controls="navBarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navBarToggler">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/about">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/projects">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/work">Work</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/cv">Curriculum Vitae</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Test-Disabled</a>
                        </li>
                    </ul>
                    <!-- I am not entirely sure if I want to include a search bar yet.
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    -->
                </div>
            </div>
        </nav>

        <main class="container">
            <?php include($local_view); ?>
        </main>
    </div>

    <footer id="sticky-footer" class="py-2 bg-dark text-white-50">
        <div class="container text-center">
            <small>&copy; Jack Whelan</small>
        </div>
    </footer>

    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap.js"></script>
    <script src="assets/js/popper.js"></script>
</body>

</html>