pipeline{
    agent{
        label "j-slave"
    }
    environment{
        REPO_NAME='portfolio'
        GITHUB_ORG='jackwhelan'
        GH_TOKEN=credentials('GH_TOKEN')
    }
    stages{
        stage("Update Commit Status to Pending") {
            steps {
                echo "========Setting Portfolio Commit Status========"
                def TARGET_URL="http://89.100.10.68:8080/job/${env.JOB_NAME}/${env.BUILD_NUMBER}/console"
                sh 'curl https://api.github.com/repos/${GITHUB_ORG}/${REPO_NAME}/statuses/${GIT_COMMIT}?access_token=${GH_TOKEN} \
                -H Accept:application/vnd.github.v3+json \
                -X POST \
                -d \'{ \
                    "state": "pending", \
                    "target_url": "$TARGET_URL" \
                }\''
            }
        }
        stage("Build"){
            steps {
                echo "========Building Portfolio========"
                sh "docker-compose build"
            }
            post{
                always{
                    echo "========cleanup========"
                    sh "docker system prune -a -f"
                }
                success{
                    echo "========Build executed successfully========"
                }
                failure{
                    echo "========Build execution failed========"
                }
            }
        }
    }
    post{
        success{
            echo "========Setting Portfolio Commit Status========"
            sh 'curl https://api.github.com/repos/${GITHUB_ORG}/${REPO_NAME}/statuses/${GIT_COMMIT}?access_token=${GH_TOKEN} \
            -H Accept:application/vnd.github.v3+json \
            -X POST \
            -d \'{ \
                "state": "success", \
                "target_url": "http://89.100.10.68:8080/job/${env.JOB_NAME}/${env.BUILD_NUMBER}/console" \
            }\''
        }
        failure{
            echo "========Setting Portfolio Commit Status========"
            sh 'curl https://api.github.com/repos/${GITHUB_ORG}/${REPO_NAME}/statuses/${GIT_COMMIT}?access_token=${GH_TOKEN} \
            -H Accept:application/vnd.github.v3+json \
            -X POST \
            -d \'{ \
                "state": "failure", \
                "target_url": "http://89.100.10.68:8080/job/${env.JOB_NAME}/${env.BUILD_NUMBER}/console" \
            }\''
        }
    }
}